# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac9fdbd009af32b1903eb3e14a4cdd8a6819ba2a90610c60937315b15410630fc2b6eda3839bdaec80f064474b747fe49dc5b1bea8a02c3f3990d83aa27503a3

test:
  secret_key_base: 42d34aca54d4e28561919083a31a6311863639f4b780efc6d25e59dc83ffde78cafcd539a2c8ed55a063b7288a011d7d61b5f220f2ddc790a366d52a9739a38d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
